pipeline {
    agent any
    stages {
        stage("Demo") {
            steps {
                script {
                    myFunc("Hello from the demo stage!")
                }
            }
        }
    }
}

def myFunc(String myText) {
    echo "myText is set to: ${myText}"
}
