pipeline{
    agent any
    parameters {
        string(defaultValue: "TEST", description: "Which environment to deploy in?", name: "deployEnv")
    }

    stages{
        stage("Demo"){
            steps{
                echo "booleanParam is set to: ${params.deployEnv}"
            }
        }
    }
}